# Configure the terminal console output
writer          = console
writer.format   = {date:yyyy-MM-DD HH:mm:ss} [{thread}] {logger}.{method}() {level}: {message}

# Global default logging level
level           = info

# SILENCE OSHI: Set its custom log level to WARN
level.oshi      = warn